### ISSUE TITLE
The location of inlay hints is not working

### ISSUE THREAD

**Issue by IWANABETHATGUY** [jrieken/test-inlayhints#1]
click the `foo` hint does not jump to the location that i give in the `InlayHintLabelPart`

https://user-images.githubusercontent.com/17974631/156958694-5ed92f60-f1cf-4e92-ab2e-dd0e4ed783cc.mp4

**Comment by jrieken** [comment]
This is just a dummy extension, nothing functional. All data is fake and it is at times out of sync with the actual API. Closing without action

**Comment by IWANABETHATGUY** [comment]
So could you please provide a sample about hot to use Inlay hint api in the latest vscode, maybe at this repo https://github.com/microsoft/vscode-extension-samples/issues/553, anyway thanks for you work.

**Comment by IWANABETHATGUY** [comment]
Any progress on this ? Another vscode version has been released but the inlayhint demo in you repo is still not available
